name: 'Create SSH folder'
description: 'Creates ssh folder with key and adds authorized key'
inputs:
  ssh_key:
    required: true
  ssh_host:
    required: true
runs:
  using: "composite"
  steps:
    - name: Create SSH folder
      run: mkdir ~/.ssh/
      shell: bash

    - name: Install SSH Key
      run: echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      shell: bash
        
    - name: Adding Known Hosts
      run: ssh-keyscan -T 60 ${{ inputs.ssh_host }} > ~/.ssh/known_hosts
      shell: bash
