name: 'Create SSH key'
description: 'Creates ssh folder and add authorized key'
inputs:
  ssh_key:
    required: true
  ssh_host:
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
      
    - name: Create SSH folder
      run: mkdir ~/.ssh/
      shell: bash

    - name: Install SSH Key
      run: echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      shell: bash
        
    - name: Adding Known Hosts
      run: ssh-keyscan -T 60 ${{ inputs.ssh_host }} > ~/.ssh/known_hosts
      shell: bash
