name: 'Create SSH folder'
description: 'Creates ssh folder with key and adds authorized key'
inputs:
  ssh_key:
    required: true
  ssh_host:
    required: true
  ssh_user:
    required: true
runs:
  using: "composite"
  steps:
    - run: mkdir ~/.ssh/
      shell: bash

    - run: echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      shell: bash
        
    - run: ssh-keyscan -T 60 ${{ inputs.ssh_host }} > ~/.ssh/known_hosts
      shell: bash
      
    - run: |
        echo "
        Host host\n
        HostName {{ inputs.ssh_host }}\n
        User {{ inputs.ssh_user }}
        " > ~/.ssh/config
      shell: bash
